### ISSUE TITLE
Fire Safety infoview not showing 'watched trees'

### ISSUE THREAD

**Issue by originalfoo** [Quistar-LAB/TreeAnarchy#13]
In Fire Safety info view, when zoomed out, the trees no longer highlight with blue-red colors showing whether trees are being 'watched' by fire towers, etc.:

![image](https://user-images.githubusercontent.com/1386719/146304487-deeec844-8a73-4b29-93cf-a2add380c94b.png)

If I zoom in, they start becoming colorised:

![image](https://user-images.githubusercontent.com/1386719/146304523-98c8c458-6509-4444-973b-b047668209be.png)

In vanilla it would show fire coverage of everything in the camera view regardless of distance.

**Comment by Quistar-LAB** [comment]
I presume you're using Tree Anarchy Beta.
I'm re-working the burn tree part of tree framework in Cities Skylines, and its not done yet. Hence this issue. it'll be done soon

**Comment by originalfoo** [comment]
I'm using the stable version, not beta.

I've just noticed the tree colorisation in other info views is behaving similar way - only colorises when zoomed in. For example, Tours info view (top-left trees are uncolorised):

![image](https://user-images.githubusercontent.com/1386719/146315455-db1a23d9-2ee4-4a3c-98f5-460edac9e3f4.png)

**Comment by Quistar-LAB** [comment]
Yep, this is a bug. I'll look into it

**Comment by Quistar-LAB** [comment]
Fixed in latest Tree Anarchy Beta
