### ISSUE TITLE
Enable/Disable tree ruining?

### ISSUE THREAD

**Issue by Quistar-LAB** [Quistar-LAB/TreeAnarchy#4]
Tree ruining calls two mathf method... If ruining is removed.. should improve fps..
Though I'm not sure if to keep this as an option or to permanently remove it.

**Comment by chameleon-tbn** [comment]
Regarding to this, please consider checking compatibility with BOB that have this option included.

**Comment by Quistar-LAB** [comment]
If BOB has done it already, then I'll not consider introducing it into this mod
