### ISSUE TITLE
Loading a save made by other unlimited tree removes tree limit and delete trees

### ISSUE THREAD

**Issue by cbtendo** [Quistar-LAB/TreeAnarchy#5]
My save was using this unlimited tree: revisited mod: https://steamcommunity.com/sharedfiles/filedetails/?id=2378914031
Loading a save made using that mod with this mod seems to temporarily resets the tree liimit to 250k, and deleting trees in block-shaped are if the trees are over the limit

**Comment by Quistar-LAB** [comment]
If you have the CSL mod, Can you tell if the tree limit is set to your desired limit? If it is, then its the deserialization process that's not supporting Unlimited trees: revisited.
I don't have the source code to Unlimited Trees: Revisited, so I'm not sure how to proceed debugging

**Comment by cbtendo** [comment]
yes, the limit is set to what i desired in the option. that works just fine

**Comment by cbtendo** [comment]
Wait, I was wrong. the trees are there. it's just.. not rendered until I build something near it.

**Comment by Quistar-LAB** [comment]
[TreeAnarchy.zip](https://github.com/Quistar-LAB/TreeAnarchy/files/6552411/TreeAnarchy.zip)
Please try this. I think I found the problem.
Apparently, tree snapping should not be implemented in Unlimited trees, but should be implemented with MoveIt mod. I just need to expose the possibility of saving and loading the modified Y position of the trees.

**Comment by cbtendo** [comment]
ooh so the position is not saved.
I tried using 0.2.1 using a save made with 0.2.0 with the trees position are reseted by building things. but I think the tree position is back to 0 again. 

and I after changing to 0.2.1, I tested plopping several trees in empty area, raising them with move it until it floats in the air. save the game, quit to desktop, and loading the save. after loading save, the new tree is gone (not sunk, can't select any tree with move it in the planted area)

**Comment by Quistar-LAB** [comment]
It seems I misunderstood the way trees are stored within the buffer by Colossal Order. After a few hours of investigating it. I found out that even if you have 1 tree on the map, it could be stored anywhere in the buffer. (Even at the end of the buffer).
So in order to accommodate this issue. We will have to walkthrough the entire buffer to store the trees, and not be selective as I was doing previously.
I fixed the issue and will be releasing a new version in a few hours.

**Comment by Quistar-LAB** [comment]
[TreeAnarchy.zip](https://github.com/Quistar-LAB/TreeAnarchy/files/6557109/TreeAnarchy.zip)
I just released version 0.3.0
This release should address all the problems you've been encountering. I've described in detail what the issues were in the release tag.
Thanks for your awesome input. It really helped me find the greatest problems in this mod

**Comment by cbtendo** [comment]
uuhh.. well... updating to 0.3.0 broke the game. I got this error while loading my 0.2.1 save

Simulation error: Array index is out of range.
  at PrefabCollection`1[TreeInfo].GetPrefab (UInt32 index) [0x00000] in <filename unknown>:0 
  at TreeInstance.get_Info () [0x00000] in <filename unknown>:0 
  at TreeManager+Data.AfterDeserialize (ColossalFramework.IO.DataSerializer s) [0x00000] in <filename unknown>:0 
  at ColossalFramework.IO.DataSerializer.Deserialize[Data] (System.IO.Stream stream, Mode mode, ColossalFramework.IO.LegacyResolverHandler customResolver) [0x00000] in <filename unknown>:0 
  at ColossalFramework.IO.DataSerializer.Deserialize[Data] (System.IO.Stream stream, Mode mode) [0x00000] in <filename unknown>:0 
  at LoadingManager+<LoadSimulationData>c__IteratorB.MoveNext () [0x00000] in <filename unknown>:0 
  at AsyncTask.Execute () [0x00000] in <filename unknown>:0   [Core]

**Comment by Quistar-LAB** [comment]
hmmm can you try using one of your previously saved game which was saved using Unlimited Trees Revisited, and try loading the game again. Please make sure to save it to a new save.

**Comment by Quistar-LAB** [comment]
I suspect that it was one of the saved game that was using the previous version of this mod. If that's the case, then GetPrefab might be pointing to a wrong index.

**Comment by Quistar-LAB** [comment]
BTW loading 0.2.1 cannot be done, because the format has been changed to fix issues that was mentioned above. Please use a new game or a previous save by the original unlimited trees mod. I just remembered what I changed

**Comment by Quistar-LAB** [comment]
[TreeAnarchy-0.4.1.zip](https://github.com/Quistar-LAB/TreeAnarchy/files/6564213/TreeAnarchy-0.4.1.zip)
Please try this version out. It should fix a lot of issue regarding loading games from old Unlimited Tree mod. I found a couple bugs in my codes within the CIL sections.

**Comment by cbtendo** [comment]
With 0.4.1 the trees isn't sunk like before. all trees loaded perfectly. and new floating trees are also loaded correctly and not missing. So the issue is fixed for me
